
// colour list
export const ADD_COLOUR_TO_LIST = 'ADD_COLOUR_TO_LIST'
export const NEW_COLOUR_CHANGE = 'NEW_COLOUR_CHANGE'
export const REMOVE_COLOUR_FROM_LIST = 'REMOVE_COLOUR_FROM_LIST'
export const SET_ACTIVE_COLOUR = 'SET_ACTIVE_COLOUR'
